UPDATE cases SET state = 'New York' WHERE state = 'NY' ; 
UPDATE cases SET state = 'Alabama' WHERE state = 'AL' ; 
UPDATE cases SET state = 'Mississippi' WHERE state = 'MS' ; 
UPDATE cases SET state = 'Kentucky' WHERE state = 'KY' ; 
UPDATE cases SET state = 'Delaware' WHERE state = 'DE' ; 
UPDATE cases SET state = 'Arkansas' WHERE state = 'AR' ; 
UPDATE cases SET state = 'Massachusetts' WHERE state = 'MA' ; 
UPDATE cases SET state = 'Maryland' WHERE state = 'MD' ; 
UPDATE cases SET state = 'Kansas' WHERE state = 'KS' ; 
UPDATE cases SET state = 'Tennessee' WHERE state = 'TN' ; 
UPDATE cases SET state = 'Pennsylvania' WHERE state = 'PA' ; 
UPDATE cases SET state = 'Virginia' WHERE state = 'VA' ; 
UPDATE cases SET state = 'Hawaii' WHERE state = 'HI' ; 
UPDATE cases SET state = 'Minnesota' WHERE state = 'MN' ; 
UPDATE cases SET state = 'South Dakota' WHERE state = 'SD' ; 
UPDATE cases SET state = 'Ohio' WHERE state = 'OH' ; 
UPDATE cases SET state = 'Idaho' WHERE state = 'ID' ; 
UPDATE cases SET state = 'North Dakota' WHERE state = 'ND' ; 
UPDATE cases SET state = 'West Virginia' WHERE state = 'WV' ; 
UPDATE cases SET state = 'Michigan' WHERE state = 'MI' ; 
UPDATE cases SET state = 'Rhode Island' WHERE state = 'RI' ; 
UPDATE cases SET state = 'Wisconsin' WHERE state = 'WI' ; 
UPDATE cases SET state = 'Connecticut' WHERE state = 'CT' ; 
UPDATE cases SET state = 'Florida' WHERE state = 'FL' ; 
UPDATE cases SET state = 'California' WHERE state = 'CA' ; 
UPDATE cases SET state = 'Oklahoma' WHERE state = 'OK' ; 
UPDATE cases SET state = 'Colorado' WHERE state = 'CO' ; 
UPDATE cases SET state = 'Nevada' WHERE state = 'NV' ; 
UPDATE cases SET state = 'Vermont' WHERE state = 'VT' ; 
UPDATE cases SET state = 'Washington' WHERE state = 'WA' ; 
UPDATE cases SET state = 'Washington, DC' WHERE state = 'DC' ; 
UPDATE cases SET state = 'South Carolina' WHERE state = 'SC' ; 
UPDATE cases SET state = 'Louisiana' WHERE state = 'LA' ; 
UPDATE cases SET state = 'Alaska' WHERE state = 'AK' ; 
UPDATE cases SET state = 'New Mexico' WHERE state = 'NM' ; 
UPDATE cases SET state = 'Oregon' WHERE state = 'OR' ; 
UPDATE cases SET state = 'New Hampshire' WHERE state = 'NH' ; 
UPDATE cases SET state = 'Iowa' WHERE state = 'IA' ; 
UPDATE cases SET state = 'Illinois' WHERE state = 'IL' ; 
UPDATE cases SET state = 'Arizona' WHERE state = 'AZ' ; 
UPDATE cases SET state = 'Georgia' WHERE state = 'GA' ; 
UPDATE cases SET state = 'Maine' WHERE state = 'ME' ; 
UPDATE cases SET state = 'Wyoming' WHERE state = 'WY' ; 
UPDATE cases SET state = 'New Jersey' WHERE state = 'NJ' ; 
UPDATE cases SET state = 'Texas' WHERE state = 'TX' ; 
UPDATE cases SET state = 'Missouri' WHERE state = 'MO' ; 
UPDATE cases SET state = 'Montana' WHERE state = 'MT' ; 
UPDATE cases SET state = 'Indiana' WHERE state = 'IN' ; 
UPDATE cases SET state = 'North Carolina' WHERE state = 'NC' ; 
UPDATE cases SET state = 'Utah' WHERE state = 'UT' ; 
UPDATE cases SET state = 'Nebraska' WHERE state = 'NE' ; 
